import type { BrandwatchTemplate, RenaultSite, ThreatField, TrackedEntity } from '@/types';

const entity = (
  id: string,
  type: TrackedEntity['type'],
  name: string,
  aliases: string[],
  extra: Partial<TrackedEntity> = {},
): TrackedEntity => ({ id, type, name, aliases, ...extra });

const threat = (
  id: string,
  label: string,
  category: ThreatField['category'],
  keywords: string[],
  severity: ThreatField['severity'] = 'medium',
): ThreatField => ({ id, label, category, keywords, severity });

export const RENAULT_TRACKED_ENTITIES: TrackedEntity[] = [
  entity('renault-group', 'brand', 'Renault Group', ['renault group', 'groupe renault', 'renault'], { brand: 'Renault Group' }),
  entity('renault-brand', 'brand', 'Renault', ['renault'], { brand: 'Renault' }),
  entity('dacia', 'brand', 'Dacia', ['dacia'], { brand: 'Dacia' }),
  entity('alpine', 'brand', 'Alpine', ['alpine cars', 'alpine'], { brand: 'Alpine' }),
  entity('mobilize', 'brand', 'Mobilize', ['mobilize'], { brand: 'Mobilize' }),
  entity('ampere', 'brand', 'Ampere', ['ampere renault', 'ampere'], { brand: 'Ampere' }),
  entity('horse', 'partner', 'Horse', ['horse powertrain', 'horse'], { brand: 'Horse' }),
  entity('luca-de-meo', 'executive', 'Luca de Meo', ['luca de meo', 'de meo'], { description: 'Renault Group chief executive watchlist entity.' }),
  entity('josep-maria-recasens', 'executive', 'Josep Maria Recasens', ['josep maria recasens', 'j m recasens', 'recasens']),
  entity('fabrice-cambolive', 'executive', 'Fabrice Cambolive', ['fabrice cambolive', 'cambolive']),
  entity('philippe-krief', 'executive', 'Philippe Krief', ['philippe krief', 'krief']),
  entity('jean-dominique-senard', 'executive', 'Jean-Dominique Senard', ['jean-dominique senard', 'senard']),
  entity('douai-plant', 'factory', 'Douai Plant', ['douai plant', 'douai'], { city: 'Douai', country: 'France', lat: 50.3703, lon: 3.0806 }),
  entity('sandouville-plant', 'factory', 'Sandouville Plant', ['sandouville plant', 'sandouville'], { city: 'Sandouville', country: 'France', lat: 49.4936, lon: 0.2915 }),
  entity('maubeuge-plant', 'factory', 'Maubeuge Plant', ['maubeuge plant', 'maubeuge'], { city: 'Maubeuge', country: 'France', lat: 50.2752, lon: 3.9727 }),
  entity('cleon-plant', 'factory', 'Cleon Plant', ['cleon plant', 'cléon', 'cleon'], { city: 'Cleon', country: 'France', lat: 49.3157, lon: 1.029 }),
  entity('batilly-plant', 'factory', 'Batilly Plant', ['batilly plant', 'batilly'], { city: 'Batilly', country: 'France', lat: 48.9912, lon: 5.9661 }),
  entity('palencia-plant', 'factory', 'Palencia Plant', ['palencia plant', 'palencia'], { city: 'Palencia', country: 'Spain', lat: 41.9965, lon: -4.5298 }),
  entity('valladolid-plant', 'factory', 'Valladolid Plant', ['valladolid plant', 'valladolid'], { city: 'Valladolid', country: 'Spain', lat: 41.6521, lon: -4.7286 }),
  entity('pitesti-plant', 'factory', 'Mioveni Plant', ['mioveni plant', 'pitesti plant', 'pitesti', 'mioveni'], { city: 'Mioveni', country: 'Romania', lat: 44.9595, lon: 24.941 }),
  entity('bursa-plant', 'factory', 'Bursa Plant', ['bursa plant', 'oyak renault', 'bursa'], { city: 'Bursa', country: 'Turkey', lat: 40.195, lon: 29.06 }),
  entity('tangier-plant', 'factory', 'Tangier Plant', ['tangier plant', 'tanger plant', 'renault tangier', 'tanger med'], { city: 'Tangier', country: 'Morocco', lat: 35.8856, lon: -5.5033 }),
  entity('oran-plant', 'factory', 'Oran Plant', ['oran plant', 'oran'], { city: 'Oran', country: 'Algeria', lat: 35.6971, lon: -0.6308 }),
  entity('novo-mesto-plant', 'factory', 'Novo Mesto Plant', ['novo mesto plant', 'novo mesto', 'revoz'], { city: 'Novo Mesto', country: 'Slovenia', lat: 45.803, lon: 15.1689 }),
  entity('chennai-plant', 'factory', 'Chennai Plant', ['chennai plant', 'oragadam', 'renault nissan chennai'], { city: 'Chennai', country: 'India', lat: 12.8217, lon: 80.037 }),
  entity('busan-plant', 'factory', 'Busan Plant', ['busan plant', 'renault korea', 'busan'], { city: 'Busan', country: 'South Korea', lat: 35.1796, lon: 129.0756 }),
  entity('sao-jose-dos-pinhais', 'factory', 'Sao Jose dos Pinhais Plant', ['sao jose dos pinhais', 'curitiba plant', 'curitiba'], { city: 'Curitiba', country: 'Brazil', lat: -25.5318, lon: -49.2031 }),
  entity('santa-isabel', 'factory', 'Santa Isabel Plant', ['santa isabel plant', 'cordoba plant', 'cordoba'], { city: 'Cordoba', country: 'Argentina', lat: -31.4201, lon: -64.1888 }),
  entity('valeo', 'supplier', 'Valeo', ['valeo']),
  entity('forvia', 'supplier', 'Forvia', ['forvia', 'faurecia']),
  entity('verkor', 'supplier', 'Verkor', ['verkor']),
  entity('lg-energy-solution', 'supplier', 'LG Energy Solution', ['lg energy solution', 'lges']),
  entity('arcelormittal', 'supplier', 'ArcelorMittal', ['arcelormittal']),
];

export const RENAULT_SITES: RenaultSite[] = [
  { id: 'boulogne-billancourt-hq', entityId: 'renault-group', name: 'Boulogne-Billancourt HQ', type: 'hq', city: 'Boulogne-Billancourt', country: 'France', lat: 48.8397, lon: 2.2399, description: 'Renault Group headquarters and executive risk anchor.' },
  { id: 'guyancourt-technocentre', entityId: 'renault-group', name: 'Guyancourt Technocentre', type: 'engineering', city: 'Guyancourt', country: 'France', lat: 48.7734, lon: 2.0735, description: 'Engineering and product development center.' },
  { id: 'douai-plant', entityId: 'douai-plant', name: 'Douai Plant', type: 'factory', city: 'Douai', country: 'France', lat: 50.3703, lon: 3.0806 },
  { id: 'sandouville-plant', entityId: 'sandouville-plant', name: 'Sandouville Plant', type: 'factory', city: 'Sandouville', country: 'France', lat: 49.4936, lon: 0.2915 },
  { id: 'maubeuge-plant', entityId: 'maubeuge-plant', name: 'Maubeuge Plant', type: 'factory', city: 'Maubeuge', country: 'France', lat: 50.2752, lon: 3.9727 },
  { id: 'cleon-plant', entityId: 'cleon-plant', name: 'Cléon Plant', type: 'factory', city: 'Cléon', country: 'France', lat: 49.3157, lon: 1.029 },
  { id: 'batilly-plant', entityId: 'batilly-plant', name: 'Batilly Plant', type: 'factory', city: 'Batilly', country: 'France', lat: 48.9912, lon: 5.9661 },
  { id: 'palencia-plant', entityId: 'palencia-plant', name: 'Palencia Plant', type: 'factory', city: 'Palencia', country: 'Spain', lat: 41.9965, lon: -4.5298 },
  { id: 'valladolid-plant', entityId: 'valladolid-plant', name: 'Valladolid Plant', type: 'factory', city: 'Valladolid', country: 'Spain', lat: 41.6521, lon: -4.7286 },
  { id: 'pitesti-plant', entityId: 'pitesti-plant', name: 'Mioveni Plant', type: 'factory', city: 'Mioveni', country: 'Romania', lat: 44.9595, lon: 24.941 },
  { id: 'bursa-plant', entityId: 'bursa-plant', name: 'Bursa Plant', type: 'factory', city: 'Bursa', country: 'Turkey', lat: 40.195, lon: 29.06 },
  { id: 'tangier-plant', entityId: 'tangier-plant', name: 'Tangier Plant', type: 'factory', city: 'Tangier', country: 'Morocco', lat: 35.8856, lon: -5.5033 },
  { id: 'oran-plant', entityId: 'oran-plant', name: 'Oran Plant', type: 'factory', city: 'Oran', country: 'Algeria', lat: 35.6971, lon: -0.6308 },
  { id: 'novo-mesto-plant', entityId: 'novo-mesto-plant', name: 'Novo Mesto Plant', type: 'factory', city: 'Novo Mesto', country: 'Slovenia', lat: 45.803, lon: 15.1689 },
  { id: 'chennai-plant', entityId: 'chennai-plant', name: 'Chennai Plant', type: 'factory', city: 'Chennai', country: 'India', lat: 12.8217, lon: 80.037 },
  { id: 'busan-plant', entityId: 'busan-plant', name: 'Busan Plant', type: 'factory', city: 'Busan', country: 'South Korea', lat: 35.1796, lon: 129.0756 },
  { id: 'tanger-med-port', entityId: 'tangier-plant', name: 'Tanger Med', type: 'logistics', city: 'Tangier', country: 'Morocco', lat: 35.8956, lon: -5.5031, description: 'Critical export and import logistics node.' },
  { id: 'le-havre-port', entityId: 'sandouville-plant', name: 'Le Havre Port', type: 'logistics', city: 'Le Havre', country: 'France', lat: 49.4944, lon: 0.1079, description: 'French Atlantic logistics chokepoint.' },
  { id: 'marseille-fos', entityId: 'renault-group', name: 'Marseille-Fos', type: 'logistics', city: 'Marseille', country: 'France', lat: 43.2965, lon: 5.3698, description: 'Mediterranean import and export gateway.' },
];

export const RENAULT_THREAT_FIELDS: ThreatField[] = [
  threat('issue-001', 'Strike calls at Renault or Ampere plants', 'labor', ['strike call', 'walkout', 'industrial action', 'union call'], 'high'),
  threat('issue-002', 'Wildcat line stoppages at Dacia or Alpine sites', 'labor', ['wildcat strike', 'line stoppage', 'production halt'], 'high'),
  threat('issue-003', 'Wage negotiations escalating with unions', 'labor', ['wage negotiation', 'salary talks', 'union talks'], 'medium'),
  threat('issue-004', 'Pension or labor reform protests blocking French sites', 'labor', ['labor reform protest', 'pension protest', 'blockade'], 'high'),
  threat('issue-005', 'Contractor unrest at factories', 'labor', ['contractor protest', 'temp worker protest', 'agency worker strike'], 'medium'),
  threat('issue-006', 'Supplier labor strike hitting Renault parts flow', 'supply-chain', ['supplier strike', 'parts supplier strike', 'supplier labor dispute'], 'high'),
  threat('issue-007', 'Port worker strikes delaying exports or imports', 'supply-chain', ['port strike', 'dockworker strike', 'harbor strike'], 'high'),
  threat('issue-008', 'Trucker blockades affecting finished-vehicle logistics', 'supply-chain', ['trucker blockade', 'road blockade', 'freight blockade'], 'high'),
  threat('issue-009', 'Dealer or service-center labor unrest', 'labor', ['dealer strike', 'service center strike', 'after-sales strike'], 'medium'),
  threat('issue-010', 'Community protests around plants or expansions', 'reputation', ['community protest', 'plant expansion protest', 'local protest'], 'medium'),
  threat('issue-011', 'Factory fire or explosion', 'industrial', ['factory fire', 'plant fire', 'explosion at plant'], 'critical'),
  threat('issue-012', 'Paint-shop or battery contamination event', 'industrial', ['contamination', 'paint shop incident', 'battery leak'], 'high'),
  threat('issue-013', 'Critical robot, press, or tooling breakdown', 'industrial', ['robot breakdown', 'tooling failure', 'press outage'], 'high'),
  threat('issue-014', 'Power outage or grid curtailment at a site', 'industrial', ['power outage', 'grid curtailment', 'electricity cut'], 'high'),
  threat('issue-015', 'Water shortage limiting production', 'industrial', ['water shortage', 'water restriction', 'water stress'], 'medium'),
  threat('issue-016', 'OT or IT outage stopping the line', 'cyber', ['it outage', 'ot outage', 'manufacturing system outage'], 'high'),
  threat('issue-017', 'Workplace injury or fatality', 'industrial', ['workplace injury', 'worker death', 'fatal accident'], 'critical'),
  threat('issue-018', 'Hazardous spill or environmental release', 'industrial', ['hazardous spill', 'chemical release', 'environmental release'], 'high'),
  threat('issue-019', 'Quality escape detected at end-of-line', 'product', ['quality issue', 'quality escape', 'end-of-line defect'], 'high'),
  threat('issue-020', 'Maintenance backlog forcing shutdown', 'industrial', ['maintenance backlog', 'planned shutdown', 'unplanned maintenance'], 'medium'),
  threat('issue-021', 'Battery cell or module shortage', 'supply-chain', ['battery shortage', 'cell shortage', 'module shortage'], 'high'),
  threat('issue-022', 'Semiconductor shortage', 'supply-chain', ['chip shortage', 'semiconductor shortage', 'microchip shortage'], 'high'),
  threat('issue-023', 'Wiring-harness shortage', 'supply-chain', ['wiring harness shortage', 'harness shortage'], 'high'),
  threat('issue-024', 'Rare-earth magnet shortage', 'supply-chain', ['rare earth shortage', 'magnet shortage'], 'medium'),
  threat('issue-025', 'Steel or aluminum squeeze', 'supply-chain', ['steel shortage', 'aluminum shortage', 'metal squeeze'], 'medium'),
  threat('issue-026', 'Tire supplier disruption', 'supply-chain', ['tire shortage', 'tire supplier disruption'], 'medium'),
  threat('issue-027', 'Seat or interior module shortage', 'supply-chain', ['seat shortage', 'interior module shortage'], 'medium'),
  threat('issue-028', 'Brake or airbag electronics shortage', 'supply-chain', ['airbag shortage', 'brake electronics shortage'], 'high'),
  threat('issue-029', 'EV motor or inverter bottleneck', 'supply-chain', ['motor shortage', 'inverter bottleneck', 'power electronics shortage'], 'high'),
  threat('issue-030', 'Supplier insolvency or bankruptcy', 'supply-chain', ['supplier bankruptcy', 'supplier insolvency', 'administration'], 'high'),
  threat('issue-031', 'Red Sea or Suez shipping disruption', 'supply-chain', ['red sea disruption', 'suez disruption', 'shipping reroute'], 'high'),
  threat('issue-032', 'Hormuz energy shock raising costs', 'geopolitical', ['hormuz', 'oil shock', 'energy shock'], 'high'),
  threat('issue-033', 'Black Sea or Mediterranean route disruption', 'supply-chain', ['black sea disruption', 'mediterranean disruption'], 'medium'),
  threat('issue-034', 'Le Havre, Marseille or Fos congestion', 'supply-chain', ['le havre congestion', 'marseille congestion', 'fos congestion'], 'high'),
  threat('issue-035', 'Rail-freight disruption to plants', 'supply-chain', ['rail disruption', 'rail strike', 'freight rail issue'], 'high'),
  threat('issue-036', 'Customs or border-clearance delays', 'supply-chain', ['customs delay', 'border delay', 'clearance issue'], 'medium'),
  threat('issue-037', 'Sanctions or export-control block on parts', 'regulatory', ['export control', 'sanctions on parts', 'trade restriction'], 'high'),
  threat('issue-038', 'Container shortage or freight-price spike', 'supply-chain', ['container shortage', 'freight spike', 'shipping rate spike'], 'medium'),
  threat('issue-039', 'Fuel shortage for logistics fleets', 'supply-chain', ['fuel shortage', 'diesel shortage', 'fuel rationing'], 'medium'),
  threat('issue-040', 'Road, bridge, or tunnel closure near a plant', 'supply-chain', ['road closure', 'bridge closure', 'tunnel closure'], 'medium'),
  threat('issue-041', 'Recall for battery fire risk', 'product', ['battery recall', 'battery fire', 'thermal runaway'], 'critical'),
  threat('issue-042', 'Recall for braking or steering defect', 'product', ['brake recall', 'steering defect', 'steering recall'], 'critical'),
  threat('issue-043', 'ADAS or software defect controversy', 'product', ['adas defect', 'software bug', 'software defect'], 'high'),
  threat('issue-044', 'Charging or range underperformance scandal', 'product', ['range scandal', 'charging issue', 'range underperformance'], 'high'),
  threat('issue-045', 'Emissions or homologation compliance issue', 'regulatory', ['emissions issue', 'homologation problem', 'type approval issue'], 'critical'),
  threat('issue-046', 'Crash-test or safety-rating setback', 'product', ['crash test', 'safety rating downgrade', 'euro ncap'], 'high'),
  threat('issue-047', 'Van or fleet reliability deterioration', 'product', ['fleet reliability', 'van reliability', 'downtime issue'], 'medium'),
  threat('issue-048', 'Spare-parts shortage hurting aftersales', 'supply-chain', ['spare parts shortage', 'after-sales delay', 'repair parts delay'], 'medium'),
  threat('issue-049', 'Dealer repair backlog angering customers', 'reputation', ['repair backlog', 'service backlog', 'dealer backlog'], 'medium'),
  threat('issue-050', 'Viral defect videos damaging trust', 'reputation', ['viral defect', 'viral video', 'owner complaint video'], 'high'),
  threat('issue-051', 'CEO personal scandal', 'leadership', ['ceo scandal', 'executive scandal', 'personal scandal'], 'high'),
  threat('issue-052', 'Executive corruption allegation', 'leadership', ['bribery allegation', 'corruption probe', 'executive corruption'], 'critical'),
  threat('issue-053', 'Procurement conflict-of-interest case', 'leadership', ['conflict of interest', 'procurement scandal', 'favouritism'], 'high'),
  threat('issue-054', 'Cartel or antitrust investigation', 'regulatory', ['antitrust probe', 'cartel investigation', 'competition authority'], 'critical'),
  threat('issue-055', 'Whistleblower claim on safety or compliance', 'reputation', ['whistleblower', 'internal complaint', 'safety complaint'], 'high'),
  threat('issue-056', 'Profit warning or guidance cut', 'reputation', ['profit warning', 'guidance cut', 'earnings warning'], 'high'),
  threat('issue-057', 'Accounting restatement or control weakness', 'leadership', ['restatement', 'control weakness', 'accounting issue'], 'high'),
  threat('issue-058', 'Audit, ethics, or compliance investigation', 'regulatory', ['ethics investigation', 'audit issue', 'compliance probe'], 'high'),
  threat('issue-059', 'Boardroom succession conflict', 'leadership', ['succession dispute', 'board conflict', 'governance conflict'], 'medium'),
  threat('issue-060', 'JV governance crisis', 'leadership', ['joint venture conflict', 'governance crisis', 'partner dispute'], 'medium'),
  threat('issue-061', 'Boycott campaign against Renault brands', 'reputation', ['boycott renault', 'boycott dacia', 'boycott alpine'], 'high'),
  threat('issue-062', 'Viral misinformation about a model or plant', 'reputation', ['misinformation', 'fake news', 'false rumor'], 'medium'),
  threat('issue-063', 'NGO campaign on mining or supplier abuses', 'reputation', ['ngo campaign', 'human rights campaign', 'supplier abuse'], 'high'),
  threat('issue-064', 'Backlash over layoffs or closures', 'reputation', ['layoff backlash', 'plant closure protest', 'closure backlash'], 'high'),
  threat('issue-065', 'Criticism of executive pay or bonuses', 'reputation', ['executive pay criticism', 'bonus backlash', 'pay outrage'], 'medium'),
  threat('issue-066', 'Greenwashing accusation', 'reputation', ['greenwashing', 'sustainability claim backlash', 'false green claim'], 'medium'),
  threat('issue-067', 'Offensive marketing or comms controversy', 'reputation', ['ad backlash', 'offensive campaign', 'communication controversy'], 'medium'),
  threat('issue-068', 'Ambassador or sponsorship scandal', 'reputation', ['brand ambassador scandal', 'sponsorship controversy'], 'medium'),
  threat('issue-069', 'Alpine or F1 controversy spilling into group brand', 'reputation', ['formula 1 controversy', 'f1 scandal', 'alpine controversy'], 'medium'),
  threat('issue-070', 'Customer-service or charging-app outrage', 'reputation', ['customer service outrage', 'charging app issue', 'app outage'], 'medium'),
  threat('issue-071', 'New EU tariffs or anti-dumping measures', 'regulatory', ['eu tariff', 'anti dumping', 'import duty'], 'high'),
  threat('issue-072', 'CO2 fleet-target compliance risk', 'regulatory', ['co2 target', 'fleet target', 'emissions compliance'], 'high'),
  threat('issue-073', 'Battery passport or traceability non-compliance', 'regulatory', ['battery passport', 'traceability issue', 'battery regulation'], 'medium'),
  threat('issue-074', 'Forced-labor due-diligence exposure', 'regulatory', ['forced labor', 'due diligence failure', 'supply chain law'], 'critical'),
  threat('issue-075', 'EV subsidy or scrappage-policy change', 'regulatory', ['ev subsidy cut', 'scrappage change', 'purchase incentive'], 'medium'),
  threat('issue-076', 'Local-content rule hurting market access', 'regulatory', ['local content rule', 'localisation rule', 'market access rule'], 'medium'),
  threat('issue-077', 'Privacy regulator investigation', 'cyber', ['privacy investigation', 'data protection authority', 'gdpr probe'], 'high'),
  threat('issue-078', 'Consumer-protection action on pricing or claims', 'regulatory', ['consumer protection probe', 'pricing investigation', 'advertising claim'], 'high'),
  threat('issue-079', 'Safety regulator probe or stop-sale order', 'regulatory', ['stop sale', 'regulator probe', 'safety investigation'], 'critical'),
  threat('issue-080', 'State-aid or public-subsidy dispute', 'regulatory', ['state aid', 'subsidy dispute', 'public support dispute'], 'medium'),
  threat('issue-081', 'Ransomware at plant or HQ', 'cyber', ['ransomware', 'encrypted systems', 'cyber extortion'], 'critical'),
  threat('issue-082', 'Dealer-network cyberattack', 'cyber', ['dealer cyberattack', 'dealer breach', 'retail cyber attack'], 'high'),
  threat('issue-083', 'Connected-car API or app breach', 'cyber', ['connected car breach', 'api breach', 'telematics breach'], 'critical'),
  threat('issue-084', 'Customer or employee data leak', 'cyber', ['data leak', 'data breach', 'customer data exposed'], 'critical'),
  threat('issue-085', 'Supplier cyber compromise spreading inward', 'cyber', ['supplier cyber attack', 'third party breach', 'supply chain attack'], 'high'),
  threat('issue-086', 'OT intrusion in manufacturing systems', 'cyber', ['ot intrusion', 'scada breach', 'manufacturing cyber attack'], 'critical'),
  threat('issue-087', 'Website or app outage during launch or recall', 'cyber', ['website outage', 'app outage', 'digital outage'], 'medium'),
  threat('issue-088', 'Executive phishing or impersonation campaign', 'cyber', ['phishing campaign', 'executive impersonation', 'business email compromise'], 'medium'),
  threat('issue-089', 'AI-generated disinformation targeting leaders', 'cyber', ['deepfake', 'ai disinformation', 'synthetic media'], 'medium'),
  threat('issue-090', 'Third-party SaaS outage hurting operations', 'cyber', ['saas outage', 'cloud outage', 'vendor outage'], 'medium'),
  threat('issue-091', 'Flood or heatwave hitting plant output', 'natural', ['flood', 'heatwave', 'extreme heat'], 'high'),
  threat('issue-092', 'Drought or water restrictions at a site', 'natural', ['drought', 'water restriction', 'water shortage'], 'medium'),
  threat('issue-093', 'Earthquake near a plant or supplier cluster', 'natural', ['earthquake', 'seismic event'], 'high'),
  threat('issue-094', 'Wildfire or smoke disrupting logistics', 'natural', ['wildfire', 'smoke alert', 'forest fire'], 'high'),
  threat('issue-095', 'Hurricane or typhoon hitting a hub', 'natural', ['hurricane', 'typhoon', 'cyclone'], 'high'),
  threat('issue-096', 'Political instability in a plant country', 'geopolitical', ['political instability', 'government crisis', 'martial law'], 'high'),
  threat('issue-097', 'Civil unrest in a supplier geography', 'geopolitical', ['civil unrest', 'riot', 'mass protest'], 'high'),
  threat('issue-098', 'Currency collapse or inflation shock', 'geopolitical', ['currency collapse', 'devaluation', 'inflation shock'], 'medium'),
  threat('issue-099', 'Alliance or partner crisis spilling onto Renault', 'leadership', ['alliance crisis', 'partner crisis', 'joint venture issue'], 'medium'),
  threat('issue-100', 'Critical competitor or supplier bankruptcy', 'supply-chain', ['bankruptcy', 'chapter 11', 'administration'], 'high'),
];

export const RENAULT_QUERY_TEMPLATES: BrandwatchTemplate[] = [
  {
    id: 'template-social',
    name: 'Factory Social Risk',
    description: 'Labor unrest around Renault factories and key production hubs.',
    query: '(Renault OR Dacia OR Alpine OR Ampere) AND (strike OR walkout OR union OR blockade OR protest)',
    color: '#ef4444',
  },
  {
    id: 'template-supply',
    name: 'Supply Chain Pressure',
    description: 'Parts, batteries, semiconductors, ports, and freight disruptions.',
    query: '(Renault OR Dacia OR Ampere OR Horse) AND (supplier OR battery OR semiconductor OR port OR logistics OR customs OR freight)',
    color: '#f97316',
  },
  {
    id: 'template-leadership',
    name: 'Leadership Watch',
    description: 'Executive reputation, governance, and board-level issues.',
    query: '("Luca de Meo" OR Renault OR "Renault Group") AND (scandal OR probe OR bribery OR corruption OR whistleblower OR governance)',
    color: '#8b5cf6',
  },
  {
    id: 'template-product',
    name: 'Product Safety',
    description: 'Recalls, defects, charging complaints, and safety probes.',
    query: '(Renault OR Dacia OR Alpine) AND (recall OR defect OR battery OR braking OR steering OR "stop sale")',
    color: '#dc2626',
  },
  {
    id: 'template-cyber',
    name: 'Cyber Exposure',
    description: 'Cyberattacks, data leaks, and operational technology incidents.',
    query: '(Renault OR Dacia OR Alpine OR Mobilize) AND (ransomware OR breach OR phishing OR outage OR cyberattack OR deepfake)',
    color: '#2563eb',
  },
  {
    id: 'template-regulation',
    name: 'Regulation & Compliance',
    description: 'Regulatory and legal moves affecting Renault operations.',
    query: '(Renault OR Dacia OR Alpine OR Ampere) AND (tariff OR antitrust OR emissions OR homologation OR subsidy OR GDPR)',
    color: '#f59e0b',
  },
  {
    id: 'template-french-media',
    name: 'France Media Sweep',
    description: 'High-noise media sweep for weak signals in French coverage.',
    query: '(Renault OR "Groupe Renault" OR Dacia OR Alpine OR Mobilize) AND (usine OR greve OR rappel OR enquete OR scandale OR "supply chain")',
    color: '#14b8a6',
  },
  {
    id: 'template-natural',
    name: 'Factory Weather Disruption',
    description: 'Weather and disaster exposure around production nodes.',
    query: '(Renault OR Dacia OR Ampere) AND (flood OR heatwave OR drought OR wildfire OR earthquake OR typhoon)',
    color: '#0ea5e9',
  },
];
